services:
  d2-api:
    build: .
    container_name: d2-api
    restart: always
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    networks:
      - showdown-network
    command: go run ./cmd/main.go


networks:
  showdown-network:
    external: true