services:
  d2-api:
    build: .
    image: relative-fi/d2-api
    container_name: d2-api
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - tournament-service_default
    command: go run ./cmd/main.go


networks:
  tournament-service_default:
    external: true
